apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-appname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-app
  template:
    metadata:
      labels:
        app: k8-app
    spec:
      containers:
      - name: k8-app
        image: kubereg12.azurecr.io/pj-app:{{GITHUB_SHA}}
        ports:
        - containerPort: 8080
----

apiVersion: v1
kind: Service
metadata:
  name: k8-appname-service
spec:
  selector:
    app: k8-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
