on: [push]

permissions:
  id-token: write  # Allow GitHub Actions to request an ID token
  contents: read   # Allow reading repository contents
# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: kubereg12
  CLUSTER_NAME: aks-cluster-my
  CLUSTER_RESOURCE_GROUP: kube
  NAMESPACE: aks-pj
  IMAGE_NAME: pj-app
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@master

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.5.0"  # Set your desired Terraform version
        
   # Log into Azure using the service principal credentials
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker buildx build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/{{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/{{ env.IMAGE_NAME }}:${{ github.sha }}
    
